### ISSUE TITLE
jsonpath-ng repo missing

### ISSUE THREAD

**Issue by impredicative** [tomas-fp/strekcher#1]
This issue is in the wrong place but that's because I can't seem to find the right place.

https://pypi.python.org/pypi/jsonpath-ng/ links to https://github.com/tomas-fp/python-jsonpath-ng but there is no such repo. I realize the package is a merger, but a repo would be relevant nonetheless. Thanks.

**Comment by tomas-fp** [comment]
Thanks, will fix that. The official repo is: https://github.com/h2non/jsonpath-ng

**Comment by impredicative** [comment]
BTW, its readme lists the ability to update or remove nodes, but I don't see how this is possible. There are no examples for updating or removing nodes. Actually I know how to update using parse(...).update(...) but removing is not obvious to me.
